
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.22621 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/mingw/bin/gcc.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      1
      C:\\Users\\006li\\OneDrive\\Documents\\CLion 2023.3\\bin\\mingw\\bin/ld.exe: cannot open output file a.exe: Invalid argument
      collect2.exe: error: ld returned 1 exit status
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/mingw/bin/gcc.exe 
      Build flags: 
      Id flags: -c 
      
      The output was:
      1
      Assembler messages:
      Fatal error: can't create CMakeCCompilerId.o: Invalid argument
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/mingw/bin/gcc.exe 
      Build flags: 
      Id flags: -Aa 
      
      The output was:
      1
      <command-line>: error: missing '(' after predicate
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/mingw/bin/gcc.exe 
      Build flags: 
      Id flags: -D__CLASSIC_C__ 
      
      The output was:
      1
      C:\\Users\\006li\\OneDrive\\Documents\\CLion 2023.3\\bin\\mingw\\bin/ld.exe: cannot open output file a.exe: Invalid argument
      collect2.exe: error: ld returned 1 exit status
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/mingw/bin/gcc.exe 
      Build flags: 
      Id flags: --target=arm-arm-none-eabi;-mcpu=cortex-m3 
      
      The output was:
      1
      gcc.exe: warning: '-mcpu=' is deprecated; use '-mtune=' or '-march=' instead
      gcc.exe: error: unrecognized command-line option '--target=arm-arm-none-eabi'
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/mingw/bin/gcc.exe 
      Build flags: 
      Id flags: -c;-I__does_not_exist__ 
      
      The output was:
      1
      Assembler messages:
      Fatal error: can't create CMakeCCompilerId.o: Invalid argument
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/mingw/bin/gcc.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      1
      C:\\Users\\006li\\OneDrive\\Documents\\CLion 2023.3\\bin\\mingw\\bin/ld.exe: cannot open output file a.exe: Invalid argument
      collect2.exe: error: ld returned 1 exit status
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/mingw/bin/gcc.exe 
      Build flags: 
      Id flags: -c 
      
      The output was:
      1
      Assembler messages:
      Fatal error: can't create CMakeCCompilerId.o: Invalid argument
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/mingw/bin/gcc.exe 
      Build flags: 
      Id flags: -Aa 
      
      The output was:
      1
      <command-line>: error: missing '(' after predicate
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/mingw/bin/gcc.exe 
      Build flags: 
      Id flags: -D__CLASSIC_C__ 
      
      The output was:
      1
      C:\\Users\\006li\\OneDrive\\Documents\\CLion 2023.3\\bin\\mingw\\bin/ld.exe: cannot open output file a.exe: Invalid argument
      collect2.exe: error: ld returned 1 exit status
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/mingw/bin/gcc.exe 
      Build flags: 
      Id flags: --target=arm-arm-none-eabi;-mcpu=cortex-m3 
      
      The output was:
      1
      gcc.exe: warning: '-mcpu=' is deprecated; use '-mtune=' or '-march=' instead
      gcc.exe: error: unrecognized command-line option '--target=arm-arm-none-eabi'
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/mingw/bin/gcc.exe 
      Build flags: 
      Id flags: -c;-I__does_not_exist__ 
      
      The output was:
      1
      Assembler messages:
      Fatal error: can't create CMakeCCompilerId.o: Invalid argument
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:1144 (message)"
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:86 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Checking whether the C compiler is IAR using "" did not match "IAR .+ Compiler":
      gcc.exe: fatal error: no input files
      compilation terminated.
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:1144 (message)"
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:86 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Checking whether the C compiler is IAR using "" did not match "IAR .+ Compiler":
      gcc.exe: fatal error: no input files
      compilation terminated.
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "//wsl.localhost/Ubuntu/home/sc43/a5_lxx789/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-otef2i"
      binary: "//wsl.localhost/Ubuntu/home/sc43/a5_lxx789/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-otef2i"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: ""
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: '//wsl.localhost/Ubuntu/home/sc43/a5_lxx789/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-otef2i'
        
        Run Build Command(s): "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/ninja/win/x64/ninja.exe" -v cmTC_e8f1b
        [1/2] C:\\Users\\006li\\OneDrive\\DOCUME~1\\CLION2~1.3\\bin\\mingw\\bin\\gcc.exe    -o CMakeFiles\\cmTC_e8f1b.dir\\CMakeCCompilerABI.c.obj -c "C:\\Users\\006li\\OneDrive\\Documents\\CLion 2023.3\\bin\\cmake\\win\\x64\\share\\cmake-3.28\\Modules\\CMakeCCompilerABI.c"
        FAILED: CMakeFiles/cmTC_e8f1b.dir/CMakeCCompilerABI.c.obj 
        C:\\Users\\006li\\OneDrive\\DOCUME~1\\CLION2~1.3\\bin\\mingw\\bin\\gcc.exe    -o CMakeFiles\\cmTC_e8f1b.dir\\CMakeCCompilerABI.c.obj -c "C:\\Users\\006li\\OneDrive\\Documents\\CLion 2023.3\\bin\\cmake\\win\\x64\\share\\cmake-3.28\\Modules\\CMakeCCompilerABI.c"
        Assembler messages:\x0d
        Fatal error: can't create CMakeFiles\\cmTC_e8f1b.dir\\CMakeCCompilerABI.c.obj: Invalid argument\x0d
        ninja: build stopped: subcommand failed.
        
      exitCode: 1
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/cmake/win/x64/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Check for working C compiler: C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/mingw/bin/gcc.exe"
    directories:
      source: "//wsl.localhost/Ubuntu/home/sc43/a5_lxx789/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-erwrra"
      binary: "//wsl.localhost/Ubuntu/home/sc43/a5_lxx789/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-erwrra"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: ""
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: '//wsl.localhost/Ubuntu/home/sc43/a5_lxx789/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-erwrra'
        
        Run Build Command(s): "C:/Users/006li/OneDrive/Documents/CLion 2023.3/bin/ninja/win/x64/ninja.exe" -v cmTC_3e47b
        [1/2] C:\\Users\\006li\\OneDrive\\DOCUME~1\\CLION2~1.3\\bin\\mingw\\bin\\gcc.exe    -o CMakeFiles\\cmTC_3e47b.dir\\testCCompiler.c.obj -c \\\\wsl.localhost\\Ubuntu\\home\\sc43\\a5_lxx789\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-erwrra\\testCCompiler.c
        FAILED: CMakeFiles/cmTC_3e47b.dir/testCCompiler.c.obj 
        C:\\Users\\006li\\OneDrive\\DOCUME~1\\CLION2~1.3\\bin\\mingw\\bin\\gcc.exe    -o CMakeFiles\\cmTC_3e47b.dir\\testCCompiler.c.obj -c \\\\wsl.localhost\\Ubuntu\\home\\sc43\\a5_lxx789\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-erwrra\\testCCompiler.c
        Assembler messages:\x0d
        Fatal error: can't create CMakeFiles\\cmTC_3e47b.dir\\testCCompiler.c.obj: Invalid argument\x0d
        ninja: build stopped: subcommand failed.
        
      exitCode: 1
...
